variables:
  - group: deployment
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: DownloadSecureFile@1
  name: ALGONAUTS_PRIVATE_KEY
  displayName: 'Algonauts private key'
  inputs:
    secureFile: 'algonauts.pem'
- bash: |
    mkdir ~/.ssh
    cp "$(ALGONAUTS_PRIVATE_KEY.secureFilePath)" ~/.ssh/id_rsa
    chmod 400 ~/.ssh/id_rsa
    ssh-keyscan $(HELIOS_IP) > ~/.ssh/known_hosts
    chmod 644 ~/.ssh/known_hosts
    scp -P $(HELIOS_SSH_PORT) _helios/scripts/startup/deploy.sh $(HELIOS_USER)@$(HELIOS_IP):~/deploy.sh
    ssh -p $(HELIOS_SSH_PORT) $(HELIOS_USER)@$(HELIOS_IP) "HELIOS_GIT_SOURCE=$(HELIOS_GIT_SOURCE) HELIOS_DEPLOYMENT_BRANCH=$(HELIOS_BRANCH) HELIOS_DOMAIN_NAME=$(HELIOS_DOMAIN) HELIOS_SSL_EMAIL=$(HELIOS_SSL_EMAIL) HELIOS_POSTGRES_DB=$(HELIOS_POSTGRES_DB) HELIOS_POSTGRES_USER=$(HELIOS_POSTGRES_USER) HELIOS_POSTGRES_PASSWORD=$(HELIOS_POSTGRES_PASSWORD) HELIOS_POSTGRES_HOST=$(HELIOS_POSTGRES_HOST) /bin/bash ~/deploy.sh"
    ssh -p $(HELIOS_SSH_PORT) $(HELIOS_USER)@$(HELIOS_IP) "rm deploy.sh"
trigger: none
