variables:
  - group: dev
pool:
  vmImage: 'ubuntu-18.04'
steps:
- task: DownloadSecureFile@1
  name: ALGONAUTS_PRIVATE_KEY
  displayName: 'Algonauts private key'
  inputs:
    secureFile: 'algonauts.pem'
- bash: |
    mkdir ~/.ssh
    cp "$(ALGONAUTS_PRIVATE_KEY.secureFilePath)" ~/.ssh/id_rsa
    chmod 400 ~/.ssh/id_rsa
    ssh-keyscan -p $(HELIOS_SSH_PORT) $(HELIOS_IP) > ~/.ssh/known_hosts
    chmod 644 ~/.ssh/known_hosts
    scp -P $(HELIOS_SSH_PORT) _helios/scripts/startup/update.sh $(HELIOS_USER)@$(HELIOS_IP):~/update.sh
    ssh -p $(HELIOS_SSH_PORT) $(HELIOS_USER)@$(HELIOS_IP) "ALGONAUTS_UTILS_GIT_SOURCE=$(ALGONAUTS_UTILS_GIT_SOURCE) ALGONAUTS_UTILS_GIT_BRANCH=$(ALGONAUTS_UTILS_GIT_BRANCH) HELIOS_GIT_SOURCE=$(HELIOS_GIT_SOURCE) HELIOS_DEPLOYMENT_BRANCH=$(HELIOS_BRANCH) HELIOS_POSTGRES_DB=$(HELIOS_POSTGRES_DB) HELIOS_POSTGRES_USER=$(HELIOS_POSTGRES_USER) HELIOS_POSTGRES_PASSWORD=$(HELIOS_POSTGRES_PASSWORD) HELIOS_POSTGRES_HOST=$(HELIOS_POSTGRES_HOST) sudo -E /bin/bash ~/update.sh"
    ssh -p $(HELIOS_SSH_PORT) $(HELIOS_USER)@$(HELIOS_IP) "rm update.sh"
trigger: none
